name: transporter
version: git
adopt-info: transporter
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core20
architectures:
  - build-on: amd64
    run-on: amd64
  - build-on: i386
    run-on: i386

slots:
  # for GtkApplication registration
  transporter:
    interface: dbus
    bus: session
    name: com.github.bleakgrey.transporter

apps:
  transporter:
    extensions: [ gnome-3-38 ]
    command: usr/bin/com.github.bleakgrey.transporter
    common-id: com.github.bleakgrey.transporter.desktop
    plugs:
      - home
      - network
      - removable-media

parts:
  granite:
    source: https://github.com/elementary/granite.git
    meson-parameters: [ --prefix=/usr ]
    plugin: meson
    override-pull: |
      snapcraftctl pull
      sed -i.bak -e 's|io.elementary.desktop.wingpanel.datetime|org.gnome.desktop.interface|g' lib/DateTime.vala

  wormhole:
    plugin: python
    python-packages: [ magic-wormhole ]
    build-packages:
      - libssl-dev

  transporter:
    after: [granite, wormhole]
    source: .
    source-type: git
    parse-info: [usr/share/metainfo/com.github.bleakgrey.transporter.appdata.xml]
    build-environment:
      - XDG_DATA_DIRS: $XDG_DATA_DIRS:$SNAPCRAFT_STAGE/usr/share:/usr/share
      - GI_TYPELIB_PATH: $SNAPCRAFT_STAGE/usr/lib/girepository-1.0:$SNAPCRAFT_STAGE/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/girepository-1.0:/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/girepository-1.0
    override-pull: |
      snapcraftctl pull
      sed -i.bak -e 's|magic-wormhole|wormhole|g' src/WormholeInterface.vala
      sed -i.bak -e 's|WORMHOLE_LOCATIONS = {|WORMHOLE_LOCATIONS = {"/snap/transporter/current/bin/wormhole", |g' src/WormholeInterface.vala
      sed -i.bak -e 's|Icon=com.github.bleakgrey.transporter$|Icon=${SNAP}/meta/gui/transporter.svg|g' data/com.github.bleakgrey.transporter.desktop.in
      patch -p1 < $SNAPCRAFT_PROJECT_DIR/snap/local/patches/xdg_open.patch
    override-build: |
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp data/icons/128/com.github.bleakgrey.transporter.svg $SNAPCRAFT_PART_INSTALL/meta/gui/transporter.svg
    plugin: meson
    meson-parameters:
      - --prefix=/snap/transporter/current/usr
    organize:
      snap/transporter/current/usr: usr
